[certificate]
marathon = "Run2Empower" # Use title case
date = "2024-08-04" # Format: YYYY-MM-DD (ISO 8601)
title = "Certificate of Participation"

[email]
sender = "dlrcfoundation1111@gmail.com"
password = "myrl vohc kusy rzdq1111" # your google app password
subject = "Heartfelt Gratitude from Team DLRC"

# ansh.tiwante@gmail.com : rbyw otvi xmuh srvd
# dlrcfoundation@gmail.com : 

# dlrcf1903
